---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
  - name: centos-7
    run_list:
      - recipe[build-essential]

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
      - recipe[nginx::http_geoip_module]
    verifier:
      inspec_tests:
        - test/integration/packages
        - test/integration/modules